import { Referee } from '@/lib/types';

/**
 * PLACEHOLDER REFEREE DATA
 * ========================
 * These are placeholder profiles that MUST be replaced with real referee
 * information before launch. Each profile uses neutral placeholder names
 * and generic content.
 *
 * To update: Replace each entry with real referee details including
 * name, biography, qualifications, photo, and region.
 */
export const referees: Referee[] = [
  {
    id: 'ref-01',
    slug: 'jonathan-evans',
    name: 'Jonathan Evans',
    role: 'Co-founder & Match Referee',
    region: 'South Wales',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'Co-founder with 8 years of refereeing experience.',
    fullBio: 'Jonathan Evans is a co-founder with 8 years of refereeing experience. Based in South Wales, his best times over the last 4 years have been at Heart of Wales. Fun fact: He loves a pint.',
    image: '/assets/referees/jonathan-evans.jpg',
    featured: true,
    available: true,
    order: 1,
  },
  {
    id: 'ref-02',
    slug: 'jamie-watkins',
    name: 'Jamie Watkins',
    role: 'Co-founder & Match Referee',
    region: 'Trebanos',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'Co-founder with 10 years of refereeing experience.',
    fullBio: 'Jamie Watkins is a co-founder from Trebanos with 10 years of overall experience, including 3 years at level 2. Fun fact: He can run 100m in 1 hour 🤣.',
    image: '/assets/referees/jamie-watkins.jpg',
    featured: true,
    available: true,
    order: 2,
  },
  {
    id: 'ref-03',
    slug: 'rob-brooks',
    name: 'Rob Brooks',
    role: 'Match Referee',
    region: 'Alltwen, South Wales',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'Original member with 10+ years of refereeing experience.',
    fullBio: 'Rob Brooks is an original member from Alltwen with 10+ years of refereeing experience. Fun fact: He is known to wear two "RIGHT" footed socks for obvious reasons!',
    image: '/assets/referees/rob-brooks.jpg',
    featured: true,
    available: true,
    order: 3,
  },
  {
    id: 'ref-04',
    slug: 'paul-thomas',
    name: 'Paul Thomas',
    role: 'Match Referee',
    region: 'Blaendulais',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'Experienced match referee who is still young enough to cartwheel.',
    fullBio: 'Paul Thomas, hailing from Blaendulais, has "lots" of years of refereeing experience under his belt. Fun fact: He is still young enough to cartwheel.',
    image: '/assets/referees/paul-thomas.jpg',
    featured: true,
    available: true,
    order: 4,
  },
  {
    id: 'ref-05',
    slug: 'alex-yau',
    name: 'Alex Yau',
    role: 'Co-founder & Match Referee',
    region: 'Ceredigion',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An adopted Welshman with 20+ years of experience.',
    fullBio: 'Alex Yau is a co-founder and one of the originals. Describing himself as Migrant English, Chinese, Scottish, Japanese & Italian, he is an adopted Welshman residing in Ceredigion. With 20+ years of experience and still learning, he will officiate anywhere and everywhere. Just give him 2 teams to chase and a pitch to run around with his whistle.',
    image: '/assets/referees/alex-yau.jpg',
    featured: true,
    available: true,
    order: 5,
  },
  {
    id: 'ref-06',
    slug: 'rob-lowe',
    name: 'Rob Lowe',
    role: 'Match Referee',
    region: 'Cornwall',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'HOW7s Celtic family member with 11 years of experience.',
    fullBio: 'Rob Lowe is from Cornwall and has 11 years of refereeing experience. He joined his Celtic family at HOW7s. Fun fact: He wears the same pair of pants to ref in, his "lucky ducks".',
    image: '/assets/referees/rob-lowe.jpg',
    featured: true,
    available: true,
    order: 6,
  },
  {
    id: 'ref-07',
    slug: 'lucy-rees',
    name: 'Lucy Rees',
    role: 'Match Referee',
    region: 'Wales',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'Level 3 referee who joined to develop skills and nag the men.',
    fullBio: 'Lucy Rees has been refereeing for 2 years and is a level 3 official. She joined the Dysfunctionals last year to develop her skills and nag the men. Fun fact: She played and officiated at the Principality Stadium on the same day.',
    image: '/assets/referees/lucy-rees.jpg',
    featured: false,
    available: true,
    order: 7,
  },
  {
    id: 'ref-08',
    slug: 'referee-eight',
    name: 'Referee Eight',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Fifteens'],
    shortBio: 'A composed match referee with a strong focus on player welfare and game flow.',
    fullBio: 'Referee Eight places player welfare at the centre of every decision. Their ability to read the game, communicate clearly with captains, and manage difficult situations calmly makes them a respected figure on any rugby pitch.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Player welfare', 'Senior rugby'],
    order: 8,
  },
  {
    id: 'ref-09',
    slug: 'referee-nine',
    name: 'Referee Nine',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An energetic referee who brings enthusiasm and structure to every match assignment.',
    fullBio: 'Referee Nine combines enthusiasm with disciplined officiating. Whether managing a morning session at a sevens tournament or taking charge of a standalone fifteens fixture, they bring consistent energy and reliable match control.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Festival rugby', 'Schools and youth events'],
    order: 9,
  },
  {
    id: 'ref-10',
    slug: 'referee-ten',
    name: 'Referee Ten',
    role: 'Senior Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An experienced senior referee providing mentoring and development support to the team.',
    fullBio: 'Referee Ten contributes to the ongoing development of the officiating team, providing constructive pitch-side feedback and peer mentoring. Their experience helps newer referees grow in confidence and capability, strengthening the overall quality of the squad.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Peer mentoring', 'Official development'],
    order: 10,
  },
  {
    id: 'ref-11',
    slug: 'referee-eleven',
    name: 'Referee Eleven',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens'],
    shortBio: 'A focused sevens specialist with sharp reflexes and strong tournament stamina.',
    fullBio: 'Referee Eleven is a sevens specialist who understands the unique demands of back-to-back tournament refereeing. Their fitness, quick thinking, and ability to maintain concentration across long tournament days make them a valuable asset for sevens events.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Sevens tournaments', 'High-volume match days'],
    order: 11,
  },
  {
    id: 'ref-12',
    slug: 'referee-twelve',
    name: 'Referee Twelve',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'A well-rounded match official ready for a range of fixtures and tournament formats.',
    fullBio: 'Referee Twelve rounds out the squad with reliable all-round officiating ability. Comfortable in both sevens and fifteens, they bring a steady hand and clear communication to every assignment, contributing to the consistent standard the team is built on.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['All-round officiating', 'Charity and corporate events'],
    order: 12,
  },
];

export function getRefereeBySlug(slug: string): Referee | undefined {
  return referees.find((r) => r.slug === slug);
}

export function getFeaturedReferees(): Referee[] {
  return referees.filter((r) => r.featured).sort((a, b) => a.order - b.order);
}

export function getAllReferees(): Referee[] {
  return [...referees].sort((a, b) => a.order - b.order);
}
