import { Referee } from '@/lib/types';

/**
 * PLACEHOLDER REFEREE DATA
 * ========================
 * These are placeholder profiles that MUST be replaced with real referee
 * information before launch. Each profile uses neutral placeholder names
 * and generic content.
 *
 * To update: Replace each entry with real referee details including
 * name, biography, qualifications, photo, and region.
 */
export const referees: Referee[] = [
  {
    id: 'ref-01',
    slug: 'referee-one',
    name: 'Referee One',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An experienced match referee bringing calm authority and clear communication to every fixture.',
    fullBio: 'Referee One brings a composed, player-focused approach to match officiating. Known for clear communication and consistent decision-making, they are comfortable managing fixtures across both sevens and fifteens formats. A reliable member of The Dysfunctional Referees team.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Tournament officiating', 'Multi-pitch coordination'],
    order: 1,
  },
  {
    id: 'ref-02',
    slug: 'referee-two',
    name: 'Referee Two',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'A dedicated match official with strong pitch presence and excellent game awareness.',
    fullBio: 'Referee Two combines strong positional awareness with an approachable manner that puts players and coaches at ease. Equally comfortable in fast-paced sevens or structured fifteens, they bring energy and professionalism to every assignment.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Sevens tournaments', 'Festival rugby'],
    order: 2,
  },
  {
    id: 'ref-03',
    slug: 'referee-three',
    name: 'Referee Three',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Fifteens'],
    shortBio: 'A focused and dependable referee with particular strength in fifteens match management.',
    fullBio: 'Referee Three specialises in fifteens rugby, bringing a measured approach to set-piece management and breakdown officiating. Their calm demeanour under pressure and consistent application of the laws make them a valued member of the team.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Fifteens officiating', 'Set-piece management'],
    order: 3,
  },
  {
    id: 'ref-04',
    slug: 'referee-four',
    name: 'Referee Four',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens'],
    shortBio: 'A sharp and dynamic referee ideally suited to the pace and intensity of sevens rugby.',
    fullBio: 'Referee Four thrives in the fast-paced environment of sevens rugby. With quick decision-making and excellent fitness, they keep up with the speed of the game while maintaining clear communication with players and tournament organisers.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Sevens officiating', 'Quick turnaround tournaments'],
    order: 4,
  },
  {
    id: 'ref-05',
    slug: 'referee-five',
    name: 'Referee Five',
    role: 'Assistant Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'A reliable assistant referee with strong communication and excellent touchline positioning.',
    fullBio: 'Referee Five excels in the assistant referee role, providing consistent and accurate support to the match referee. Their clear flag work and proactive communication help ensure matches are controlled effectively across both formats.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Assistant refereeing', 'Team officiating'],
    order: 5,
  },
  {
    id: 'ref-06',
    slug: 'referee-six',
    name: 'Referee Six',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens', 'Touch'],
    shortBio: 'A versatile official comfortable across multiple rugby formats and event types.',
    fullBio: 'Referee Six brings versatility to the team, confidently officiating across sevens, fifteens, and touch rugby. This adaptability makes them particularly valuable for mixed-format tournaments and festivals where officials need to switch between formats throughout the day.',
    image: '/assets/referees/placeholder.jpg',
    featured: true,
    available: true,
    specialisms: ['Multi-format officiating', 'Mixed tournaments'],
    order: 6,
  },
  {
    id: 'ref-07',
    slug: 'referee-seven',
    name: 'Referee Seven',
    role: 'Pitch Manager',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An organised pitch manager keeping tournament schedules running smoothly and safely.',
    fullBio: 'Referee Seven specialises in pitch management, ensuring that tournament schedules run on time and that transitions between matches are handled efficiently. Their organisational skills and calm communication style keep complex multi-pitch events flowing smoothly.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Pitch management', 'Tournament scheduling'],
    order: 7,
  },
  {
    id: 'ref-08',
    slug: 'referee-eight',
    name: 'Referee Eight',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Fifteens'],
    shortBio: 'A composed match referee with a strong focus on player welfare and game flow.',
    fullBio: 'Referee Eight places player welfare at the centre of every decision. Their ability to read the game, communicate clearly with captains, and manage difficult situations calmly makes them a respected figure on any rugby pitch.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Player welfare', 'Senior rugby'],
    order: 8,
  },
  {
    id: 'ref-09',
    slug: 'referee-nine',
    name: 'Referee Nine',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'An energetic referee who brings enthusiasm and structure to every match assignment.',
    fullBio: 'Referee Nine combines enthusiasm with disciplined officiating. Whether managing a morning session at a sevens tournament or taking charge of a standalone fifteens fixture, they bring consistent energy and reliable match control.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Festival rugby', 'Schools and youth events'],
    order: 9,
  },
  {
    id: 'ref-10',
    slug: 'referee-ten',
    name: 'Referee Ten',
    role: 'Referee Coach',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'A referee coach providing constructive feedback and development support to the team.',
    fullBio: 'Referee Ten contributes to the ongoing development of the officiating team, providing constructive pitch-side feedback and coaching support. Their experience helps newer referees grow in confidence and capability, strengthening the overall quality of the squad.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Referee coaching', 'Official development'],
    order: 10,
  },
  {
    id: 'ref-11',
    slug: 'referee-eleven',
    name: 'Referee Eleven',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens'],
    shortBio: 'A focused sevens specialist with sharp reflexes and strong tournament stamina.',
    fullBio: 'Referee Eleven is a sevens specialist who understands the unique demands of back-to-back tournament refereeing. Their fitness, quick thinking, and ability to maintain concentration across long tournament days make them a valuable asset for sevens events.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['Sevens tournaments', 'High-volume match days'],
    order: 11,
  },
  {
    id: 'ref-12',
    slug: 'referee-twelve',
    name: 'Referee Twelve',
    role: 'Match Referee',
    region: 'Region TBC',
    formats: ['Sevens', 'Fifteens'],
    shortBio: 'A well-rounded match official ready for a range of fixtures and tournament formats.',
    fullBio: 'Referee Twelve rounds out the squad with reliable all-round officiating ability. Comfortable in both sevens and fifteens, they bring a steady hand and clear communication to every assignment, contributing to the consistent standard the team is built on.',
    image: '/assets/referees/placeholder.jpg',
    featured: false,
    available: true,
    specialisms: ['All-round officiating', 'Charity and corporate events'],
    order: 12,
  },
];

export function getRefereeBySlug(slug: string): Referee | undefined {
  return referees.find((r) => r.slug === slug);
}

export function getFeaturedReferees(): Referee[] {
  return referees.filter((r) => r.featured).sort((a, b) => a.order - b.order);
}

export function getAllReferees(): Referee[] {
  return [...referees].sort((a, b) => a.order - b.order);
}
